### ISSUE TITLE
missing multisense in some xacro files?

### ISSUE THREAD

**Issue by mauricefallon** [NASA-JSC-Robotics/val_description#32]
@manuelli asked me to look into creating a urdf for the mass sim stubs. 

I noticed that the A/B/C xacro files contain a multisense include and the valkyrie_sim ones don't.
As a result the generated URDFs dont contain the sensor.

I'm looking at the files in:
https://github.com/NASA-JSC-Robotics/val_description/tree/develop/model/robots

These contain the multisense include:
- valkyrie_sim.xacro	
- valkyrie_sim_arm_mass_sims.xacro	

```    <xacro:include filename="$(find val_description)/model/urdf/multisense_sl.urdf" /> ```

These don't mention the multisense:
- valkyrie_B.xacro
- valkyrie_B_arm_mass_sims.xacro

**Comment by jlack1987** [comment]
@mauricefallon the hardware URDF's don't have the multisense included. I know we had a reason for doing it this way, but i'm having trouble remembering why. @dljsjr do you remember why we did it this way? I think it had something to do with the multisense data namespacing which is already done by the multisense or something like that.

**Comment by dljsjr** [comment]
When running the real multisense head, the Multisense ROS driver and it's corresponding node broadcast the transform tree for the head itself in a much more accurate way by masquerading their internal camera and LIDAR axis calibration data as transformations in the tf tree. Because of this, it is recommended when running the real robot that vendors broadcast a TF tree containing their robot model and also a static transform riding their model with the Multisense, then allowing for the Multisense node to broadcast the transforms for the head's internals.

There is no issue with making a "fused" URDF for simulation purposes, though, unless your sim is relying on a separate Multisense node as well. This is what we do for Atlas; sim model is complete, real robot model is missing the head and we broadcast a static transform joining the real robot to the head.

**Comment by mauricefallon** [comment]
Thanks @dljsjr , that fully answers my question. My first sentence above was incorrectly written - but you have parsed what I meant correctly.

I'm very familiar with the Carnegie Robotics calibration TF tree.
